# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-10-16 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fornecedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=100)),
                ('forma_med_part', models.FloatField(null=True)),
                ('mass_esp_apar', models.FloatField(null=True)),
                ('poros_apar', models.FloatField(null=True)),
                ('resist_int', models.FloatField(null=True)),
                ('resist_comp', models.FloatField(null=True)),
                ('resist_choq', models.FloatField(null=True)),
                ('teor_frag', models.FloatField(null=True)),
                ('mat_pulv', models.FloatField(null=True)),
                ('torr_arg', models.FloatField(null=True)),
                ('limit_m_u', models.FloatField(null=True)),
                ('resist_desg', models.FloatField(null=True)),
                ('dist_635', models.FloatField(null=True)),
                ('dist_500', models.FloatField(null=True)),
                ('dist_380', models.FloatField(null=True)),
                ('dist_250', models.FloatField(null=True)),
                ('dist_190', models.FloatField(null=True)),
                ('dist_127', models.FloatField(null=True)),
            ],
        ),
    ]
